### ISSUE TITLE
Compatibility with TeamCity 9.0.x

### ISSUE THREAD

**Issue by mar99** [dmitry-treskunov/TeamCity-AllBuildsView#2]
When I use the plugin with TeamCity 9.0.3 there appears only a blank page and I get the following stack trace

[2015-03-17 13:53:57,629]   WARN - ildServer.util.EventDispatcher - Error in event handler: java.lang.AbstractMethodError: org.jetbrains.teamcity.plugins.allbuilds.PreventFrequentMessagesFilter.filter(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Lorg/atmosphere/cpr/BroadcastFilter$BroadcastAction; (enable debug to see stacktrace) 
[2015-03-17 13:53:57,629]  DEBUG - ildServer.util.EventDispatcher - Error in event handler 
java.lang.AbstractMethodError: org.jetbrains.teamcity.plugins.allbuilds.PreventFrequentMessagesFilter.filter(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Lorg/atmosphere/cpr/BroadcastFilter$BroadcastAction;
    at org.atmosphere.cpr.BroadcasterConfig.filter(BroadcasterConfig.java:433)
    at org.atmosphere.cpr.DefaultBroadcaster.filter(DefaultBroadcaster.java:1258)
    at org.atmosphere.cpr.DefaultBroadcaster.broadcast(DefaultBroadcaster.java:1224)
    at org.atmosphere.cpr.MetaBroadcaster.broadcast(MetaBroadcaster.java:120)
    at org.atmosphere.cpr.MetaBroadcaster.map(MetaBroadcaster.java:152)
    at org.atmosphere.cpr.MetaBroadcaster.broadcastTo(MetaBroadcaster.java:163)
    at org.jetbrains.teamcity.plugins.allbuilds.BuildUpdatesHandler$BuildsNotificationsListener.broadcast(BuildUpdatesHandler.java:85)
    at org.jetbrains.teamcity.plugins.allbuilds.BuildUpdatesHandler$BuildsNotificationsListener.messageReceived(BuildUpdatesHandler.java:70)
    at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:117)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:2)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:8)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:26)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:14)
    at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
    at com.sun.proxy.$Proxy18.messageReceived(Unknown Source)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.doProcessMessage(RunningBuildImpl.java:241)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.processMessage(RunningBuildImpl.java:107)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.addBuildMessages(RunningBuildImpl.java:105)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.access$100(RunningBuildImpl.java:382)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl$2.doInTransactionWithoutResult(RunningBuildImpl.java:1)
    at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.addAgentBuildMessages(RunningBuildImpl.java:590)
    at jetbrains.buildServer.serverSide.impl.BuildAgentMessagesQueue.doProcessMessages(BuildAgentMessagesQueue.java:23)
    at jetbrains.buildServer.serverSide.impl.BuildAgentMessagesQueue.access$700(BuildAgentMessagesQueue.java:47)
    at jetbrains.buildServer.serverSide.impl.BuildAgentMessagesQueue$BuildMessagesQueue$1.run(BuildAgentMessagesQueue.java:2)
    at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
    at jetbrains.buildServer.serverSide.impl.BuildAgentMessagesQueue$BuildMessagesQueue.processMessages(BuildAgentMessagesQueue.java:8)
    at jetbrains.buildServer.serverSide.impl.BuildAgentMessagesQueue$2.run(BuildAgentMessagesQueue.java:3)
    at java.lang.Thread.run(Thread.java:745)

**Comment by dmitry-treskunov** [comment]
fixed https://github.com/dmitry-treskunov/TeamCity-AllBuildsView/releases/tag/9.x
